services:
  - type: web
    name: selection-way-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: BOT_TOKEN
        value: 8439511623:A4EEynrraSmPULZZQ1RIurKtcYn_7IxALLI
        sync: false
